service: retrieve-result

package:
  individually: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - s3:PutObject
        - s3:GetObject
      Resource: "*"

functions:
  business:
    handler: index.handle
    memorySize: 1028
    timeout: 100
    description: business retrieval service.
    events:
      - http:
          path: result/get/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
    environment:
      FILE_TABLE_NAME: Image_Classification
      S3_BUCKET_NAME: "classification-bucket-0009-6572-9629"
      REGION: "ca-central-1"
